swagger: "2.0"
info:
  version: "0.0.1"
  title: Movecare Users API
# during dev, should point to your local machine
host: 54.93.97.25:10011
#host: 54.93.97.25:10011
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /message:
    # message controller
    x-swagger-router-controller: message
    post:
      #message info to be stored
      description: add a new message
      operationId : newMessage
      parameters:
        - name : newMessage
          description : Message to be stored
          in : body
          required : true
          schema :
            $ref : "#/definitions/Message"
      responses:
        "200" :
          description : Success
          schema :
            $ref : "#/definitions/NewElementAdded"
        default :
          description : Error
          schema:
            $ref : "#/definitions/ErrorResponsePost"
            
  /allmessages:
    # binds a127 app logic to a route
    x-swagger-router-controller: message
    get:
      description: Returns the list of messages in the db
      # used as the method name of the controller
      operationId: allmessages
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetMessageListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /allcalls:
    # binds a127 app logic to a route
    x-swagger-router-controller: call
    get:
      description: Returns the list of calls in the db
      # used as the method name of the controller
      operationId: allCalls
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetCallListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /call:
    # call controller
    x-swagger-router-controller: call
    post:
      #message info to be stored
      description: add a new call
      operationId : newCall
      parameters:
        - name : newCall
          description : Call to be stored
          in : body
          required : true
          schema :
            $ref : "#/definitions/Call"
      responses:
        "200" :
          description : Success
          schema :
            $ref : "#/definitions/NewElementAdded"
        default :
          description : Error
          schema:
            $ref : "#/definitions/ErrorResponsePost"
            
  /allsmartphoneuse:
    # binds a127 app logic to a route
    x-swagger-router-controller: smartphoneUse
    get:
      description: Returns the list of smartphoneUse in the db
      # used as the method name of the controller
      operationId: allsmartphoneuse
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetSmartphoneUseListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /smartphoneuse:
    # smartphoneuse controller
    x-swagger-router-controller: smartphoneUse
    post:
      #message info to be stored
      description: add a new SmartphoneUse
      operationId : newSmartphoneUse
      parameters:
        - name : newSmartphoneUse
          description : SmartphoneUse to be stored
          in : body
          required : true
          schema :
            $ref : "#/definitions/SmartphoneUse"
      responses:
        "200" :
          description : Success
          schema :
            $ref : "#/definitions/NewElementAdded"
        default :
          description : Error
          schema:
            $ref : "#/definitions/ErrorResponsePost"
  
  /allpeopleuse:
    # binds a127 app logic to a route
    x-swagger-router-controller: peopleUse
    get:
      description: Returns the list of peopleUse in the db
      # used as the method name of the controller
      operationId: allpeopleuse
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetPeopleUseListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /peopleuse:
    # message controller
    x-swagger-router-controller: peopleUse
    post:
      #message info to be stored
      description: add a new PeopleUse
      operationId : newPeopleUse
      parameters:
        - name : newPeopleUse
          description : PeopleUse to be stored
          in : body
          required : true
          schema :
            $ref : "#/definitions/PeopleUse"
      responses:
        "200" :
          description : Success
          schema :
            $ref : "#/definitions/NewElementAdded"
        default :
          description : Error
          schema:
            $ref : "#/definitions/ErrorResponsePost"
            
  /swagger:
    x-swagger-pipe: swagger_raw
    
# complex objects have schema definitions
definitions:
  GetMessageListResponse:
    required:
      - messages
    properties:
      # The array of movies
      messages:
        type: array
        items:
          type: object
          properties:
            userid:
              type: string
            number:
              type: number
  GetCallListResponse:
    required:
      - calls
    properties:
      # The array of movies
      calls:
        type: array
        items:
          type: object
          properties:
            userid:
              type: string
            number:
              type: number
              
  GetSmartphoneUseListResponse:
    required:
      - smartphoneUses
    properties:
      # The array of movies
      smartphoneUses:
        type: array
        items:
          type: object
          properties:
            userid:
              type: string
            icode:
              type: string
  
  GetPeopleUseListResponse:
    required:
      - peopleUses
    properties:
      # The array of movies
      peopleUses:
        type: array
        items:
          type: object
          properties:
            userid:
              type: string
            icode:
              type: string
              
  NewElementAdded:
    type: object
    properties:
      success:
        type: boolean
        description: returns true if successful
    required:
      - success
      
  ErrorResponsePost:
    type: object
    properties:
      success:
        type: boolean
        description: returns false if successful
      error:
        type: string
        description: message error description
    required:
      - success
      - error
      
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  Message:
    type: object
    properties:
      userid:
        type: string
        description: User id value
      mcode:
        type: string
        description: Mcode value
      sensorid:
        type: string
        description: The sensor id
      time:
        $ref: '#/definitions/DateValue'
      data:
        type: object
        description: The data object
        items: 
          $ref: '#/definitions/ItemsMessageArray'
    required:
      - userid
      - mcode
      
  Call:
    type: object
    properties:
      userid:
        type: string
        description: User id value
      mcode:
        type: string
        description: Mcode value
      sensorid:
        type: string
        description: The sensor id
      time:
        $ref: '#/definitions/DateValue'
      data:
        type: object
        description: The data object
        items: 
          $ref: '#/definitions/ItemsCallArray'
    required:
      - userid
      - mcode
  
  SmartphoneUse:
    type: object
    properties:
      userid:
        type: string
        description: User id value
      icode:
        type: string
        description: Icode value
      time:
        $ref: '#/definitions/DateValue'
      data:
        type: object
        description: The data object
        items: 
          $ref: '#/definitions/ItemsSmartphoneUseArray'
    required:
      - userid
      - icode
  
  PeopleUse:
    type: object
    properties:
      userid:
        type: string
        description: User id value
      icode:
        type: string
        description: Icode value
      time:
        $ref: '#/definitions/DateValue'
      data:
        type: object
        description: The data object
        items: 
          $ref: '#/definitions/ItemsPeopleUseArray'
    required:
      - userid
      - icode
      
  DateValue:
    type: object
    properties:
      temporality:
        type: string
        description: The temporality, choosen between datestamp, timestamp and timeinterval
      dt:
        type: string
        description: The datestamp value
        
  ItemsMessageArray:
    type: array
    description: Items array
    items: 
      $ref: '#/definitions/SingleMessageItem'
  
  ItemsCallArray:
    type: array
    description: Items array
    items: 
      $ref: '#/definitions/SingleCallItem'
  
  ItemsSmartphoneUseArray:
    type: array
    description: Items array
    items: 
      $ref: '#/definitions/SingleSmartphoneUseItem'
      
  ItemsPeopleUseArray:
    type: array
    description: Items array
    items: 
      $ref: '#/definitions/SinglePeopleUseItem'
      
  SingleMessageItem:
    type: object
    properties:
      number: 
        type: number
        description: The sender or recipient number
      type:
        type: string
        description: The type of message, choosen between IN or OUT
      time:
        type: string
        description: The time at which the message is received or sent
  
  SingleCallItem:
    type: object
    properties:
      number: 
        type: number
        description: The caller or recipient number
      duration:
        type: number
        description: The call duration
      type:
        type: string
        description: The type of call, choosen between IN or OUT
      time:
        type: string
        description: The time at which the call is received or sent
  
  SingleSmartphoneUseItem:
    type: object
    properties:
      name: 
        type: string
        description: The name of the indicator
      value:
        type: number
        description: The value of the indicator
      units:
        type: string
        description: The units of the value, in this case choosen between SECONDS or INTEGER (in this case)
        
  SinglePeopleUseItem:
    type: object
    properties:
      log: 
        type: string
        description: The log of the item, choosen between M or C (message or call)
      number:
        type: number
        description: The last four digits of caller/recipient or sender/recipient number
      total:
        type: number
        description: The total number of call or messages made by this person
      type:
        type: string
        description: The type of call or message, choosen between IN or OUT
      duration:
        type: string
        description: The duration of the call (valid only for call elements)

